name: 'Basic'
on: [ push, pull_request, workflow_dispatch ]
jobs:
  test:
    name: test
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: bazelbuild/setup-bazelisk@v3
    - name: Mount bazel cache  # Optional
      uses: actions/cache@v4
      with:
        path: "~/.cache/bazel"
        key: bazel
    - run: bazel run :test